MKIII update

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -6,385 +6,25 @@
 #
 ##########################################################################################
 
-##########################################################################################
-# PREP WORK
-##########################################################################################
+# Temp Installer Path
+export TMPDIR=/dev/tmp; export INSTALLER=$TMPDIR/install; export OUTFD=$2; export ZIP=$3
 
-# DETECT WHETHER IN BOOT MODE
-ps | grep zygote | grep -v grep >/dev/null && BOOTMODE=true || BOOTMODE=false
-$BOOTMODE || ps -A 2>/dev/null | grep zygote | grep -v grep >/dev/null && BOOTMODE=true
-
-# TEMP INSTALLER PATH
-TMPDIR=/dev/tmp
-INSTALLER=$TMPDIR/install
-
-# MAGISK PATHS
-MAGISKBIN=/data/adb/magisk
-MOUNTPATH=$TMPDIR/magisk_img
-$BOOTMODE && IMG=/data/adb/magisk_merge.img
-
-# OTHER VARIABLES
-ZIP=$3
-MAGISK=true
-DYNAMICOREO=false
-DYNAMICAPP=false
-case $ZIP in
-  *sysover*|*Sysover*|*SYSOVER*) SYSOVERRIDE=true;;
-  *) SYSOVERRIDE=false;;
-esac
-
-# DEFAULT PERMISSIONS
+# Default Permissions
 umask 022
 
-# INITIAL CLEANUP
+# Initial Cleanup
 rm -rf $TMPDIR 2>/dev/null
 mkdir -p $INSTALLER
 
-# GET OUTFD
-OUTFD=$2
-readlink /proc/$$/fd/$OUTFD 2>/dev/null | grep /tmp >/dev/null
-if [ "$?" -eq "0" ]; then
-  OUTFD=0
-  for FD in `ls /proc/$$/fd`; do
-    readlink /proc/$$/fd/$FD 2>/dev/null | grep pipe >/dev/null
-    if [ "$?" -eq "0" ]; then
-    ps | grep " 3 $FD " | grep -v grep >/dev/null
-    if [ "$?" -eq "0" ]; then
-      OUTFD=$FD
-      break
-    fi
-    fi
-  done
-fi
+# Extract Unityfiles
+unzip -o "$ZIP" 'common/unityfiles.tar.gz' -d $INSTALLER >&2
+[ -f "$INSTALLER/common/unityfiles.tar.gz" ] || { echo "! Unable to extract zip file !"; exit 1; }
 
-# NEED THIS LOADED BEFORE UTIL_FUNCTIONS
-ui_print() {
-  $BOOTMODE && echo "$1" || echo -e "ui_print $1\nui_print" >> /proc/self/fd/$OUTFD
-}
-
-##########################################################################################
-# SETUP (UN)/INSTALL
-##########################################################################################
-
-# UNZIP FILES
-ui_print " "
-ui_print "Unzipping files..."
-unzip -o "$ZIP" -d $INSTALLER 2>/dev/null
-
-[ ! -f $INSTALLER/config.sh ] && { ui_print "! Unable to extract zip file !"; exit 1; }
-
-# LOAD FUNCTIONS
-. $INSTALLER/common/unityfiles/util_functions.sh
-
-[ "$(grep_prop id $INSTALLER/module.prop)" == "UnityTemplate" ] && { ui_print "! Unity Template is not a separate module !"; abort "! This template is for devs only !"; }
-
-# INSERT MODULE INFO INTO CONFIG.SH
-for TMP in version name author; do
-  NEW=$(grep_prop $TMP $INSTALLER/module.prop)
-  [ "$TMP" == "author" ] && NEW="by ${NEW}"
-  CHARS=$((${#NEW}-$(echo "$NEW" | tr -cd "©®™" | wc -m)))
-  SPACES=""
-  if [ $CHARS -le 41 ]; then
-    for i in $(seq $(((41-$CHARS) / 2))); do
-      SPACES="${SPACES} "
-    done
-  fi
-  if [ $(((41-$CHARS) % 2)) == 1 ]; then sed -i "s/<$TMP>/$SPACES$NEW${SPACES} /" $INSTALLER/config.sh; else sed -i "s/<$TMP>/$SPACES$NEW$SPACES/" $INSTALLER/config.sh; fi
-done
-
-. $INSTALLER/config.sh
-
-# PRINT MOD NAME
-print_modname
-
-# MOUNT DATA AND CACHE
-ui_print "- Mounting /data, /cache"
-is_mounted /data || mount /data || is_mounted /cache || mount /cache || { ui_print "! Unable to mount partitions"; exit 1; }
-
-script_type() {
-  supersuimg_mount
-  SHEBANG="#!/system/bin/sh"; ROOTTYPE="other root or rootless"; MODPATH=/system/etc/init.d; SEINJECT=/sbin/sepolicy-inject
-  if [ "$supersuimg" ] || [ -d /su ]; then
-    SHEBANG="#!/su/bin/sush"; ROOTTYPE="systemless SuperSU"; MODPATH=/su/su.d; SEINJECT=supolicy
-  elif [ -e "$(find /data /cache -name supersu_is_here | head -n1)" ]; then
-    SHEBANG="#!/su/bin/sush"; ROOTTYPE="systemless SuperSU"
-    MODPATH=$(dirname `find /data /cache -name supersu_is_here | head -n1`)/su.d
-    SEINJECT=supolicy
-  elif [ -d /system/su ] || [ -f /system/xbin/daemonsu ] || [ -f /system/xbin/sugote ]; then
-    MODPATH=/system/su.d; SEINJECT=supolicy; ROOTTYPE="system SuperSU"
-  elif [ -f /system/xbin/su ]; then
-    if [ "$(grep "SuperSU" /system/xbin/su)" ]; then
-      MODPATH=/system/su.d; ROOTTYPE="system SuperSU"; SEINJECT=supolicy
-    else
-      ROOTTYPE="LineageOS SU"
-    fi
-  fi
-}
-
-set_vars() {
-  SYS=/system
-  if [ -d /system/priv-app ]; then OLDAPP=false; else OLDAPP=true; fi
-  if $BOOTMODE; then
-    MOD_VER="/sbin/.core/img/$MODID/module.prop"
-    OLD_AML_VER="/sbin/.core/img/audmodlib/module.prop"
-  else
-    MOD_VER="$MODPATH/module.prop"
-    OLD_AML_VER="$MOUNTPATH/audmodlib/module.prop"
-  fi
-  INFO="$MODPATH/$MODID-files"
-  PROP=$MODPATH/system.prop
-  if $MAGISK && ! $SYSOVERRIDE; then
-    VEN=/system/vendor
-    UNITY="$MODPATH"
-  else
-    UNITY=""
-    if [ -d /system/addon.d ]; then
-      INFO=/system/addon.d/$MODID-files
-    else
-      INFO=/system/etc/$MODID-files
-    fi
-    if $MAGISK && $SYSOVERRIDE; then
-      patch_script $INSTALLER/common/unityfiles/modidsysover.sh
-      sed -i -e "/# CUSTOM USER SCRIPT/ r $INSTALLER/common/uninstall.sh" -e '/# CUSTOM USER SCRIPT/d' $INSTALLER/common/unityfiles/modidsysover.sh
-      cp_ch_nb $INSTALLER/common/unityfiles/modidsysover.sh $MOUNTPATH/.core/post-fs-data.d/$MODID-sysover.sh 0755 false
-    else
-      # DETERMINE SYSTEM BOOT SCRIPT TYPE
-      script_type
-      PROP=$MODPATH/$MODID-props.sh
-      MOD_VER="/system/etc/$MODID-module.prop"
-      OLD_AML_VER="/system/etc/audmodlib-module.prop"
-    fi
-  fi
-  if $DYNAMICOREO && [ $API -ge 26 ]; then 
-    LIBPATCH="\/vendor"; LIBDIR=$VEN
-  else 
-    LIBPATCH="\/system"; LIBDIR=/system
-  fi
-}
-
-# INSTALL
-unity_install() {
-  ui_print " "
-  ui_print "- Installing"
-
-  # MAKE INFO FILE
-  rm -f $INFO
-  mktouch $INFO
-    
-  # RUN USER INSTALL SCRIPT
-  . $INSTALLER/common/install.sh
-  
-  # INSTALL SCRIPTS
-  if $MAGISK; then
-    ui_print "   Installing scripts for MagiskSU..."
-    # AUTO MOUNT
-    $AUTOMOUNT && ! $SYSOVERRIDE && mktouch $MODPATH/auto_mount
-    # UPDATE INFO FOR MAGISK MANAGER
-    if $BOOTMODE; then
-      mktouch /sbin/.core/img/$MODID/update
-      cp_ch_nb $INSTALLER/module.prop $MODPATH/module.prop
-    fi
-  else
-    ui_print "   Installing scripts for $ROOTTYPE..."
-    [ "$ROOTTYPE" == "LineageOS SU" -o "$ROOTTYPE" == "other root or rootless" ] && { ui_print " "; ui_print "   ! This root method has no boot script support !"; ui_print "   ! You will need to add init.d support !"; ui_print " "; }
-  fi
-  if ! $MAGISK || $SYSOVERRIDE; then
-    # INSTALL ROM BACKUP SCRIPT
-    if [ -d /system/addon.d ]; then
-      ui_print "   Installing addon.d backup script..."
-      sed -i "s/<MODID>/$MODID/" $INSTALLER/common/unityfiles/addon.sh
-      cp_ch_nb $INSTALLER/common/unityfiles/addon.sh /system/addon.d/$MODID.sh 0755
-    else
-      ui_print "   ! Addon.d not detected. Backup script not installed..."
-    fi
-  fi
-  
-  # HANDLE REPLACE FOLDERS
-  for TARGET in $REPLACE; do
-    if $MAGISK; then mktouch $MODPATH$TARGET/.replace; else rm -rf $TARGET; fi
-  done
-  
-  # PROP FILES - add prop function for system installs
-  $PROPFILE && { prop_process $INSTALLER/common/system.prop; $MAGISK || echo $PROP >> $INFO; }
-  
-  # MODULE INFO
-  cp_ch_nb $INSTALLER/module.prop $MOD_VER
-  
-  #INSTALL POST-FS-DATA MODE SCRIPTS
-  $POSTFSDATA && install_script $INSTALLER/common/post-fs-data.sh
-  
-  # SERVICE MODE SCRIPTS
-  $LATESTARTSERVICE && install_script $INSTALLER/common/service.sh -ls
-   
-  # INSTALL FILES
-  ui_print "   Installing files for $ARCH SDK $API device..."
-  rm -f $INSTALLER/system/placeholder
-  $IS64BIT || rm -rf $INSTALLER/system/lib64 $INSTALLER/system/vendor/lib64
-  for FILE in $(find $INSTALLER/system -type f | sed "s|$INSTALLER||"); do
-    if $DYNAMICAPP; then
-      if $OLDAPP; then FILE2=$(echo $FILE | sed 's|/system/app/.*/|/system/app/|'); else FILE2=$(echo $FILE | sed 's|/system/app/|/system/priv-app/|'); fi
-    else
-      FILE2=$FILE
-    fi
-    if $DYNAMICOREO && [ $API -ge 26 ]; then
-      case $FILE in
-        /system/lib/modules/*) FILE2=$FILE;;
-        /system/lib/*) FILE2=$(echo $FILE | sed "s|/system/|$VEN/|");;
-      esac
-    fi
-    cp_ch $INSTALLER$FILE $UNITY$FILE2
-  done
-  
-  # ADD BLANK LINE TO END OF ALL PROP/SCRIPT FILES IF NOT ALREADY PRESENT
-  for FILE in $MODPATH/*.sh $MODPATH/*.prop; do
-    [ -f $FILE ] && { [ "$(tail -1 $FILE)" ] && echo "" >> $FILE; }
-  done
-  
-  # REMOVE INFO FILE IF NOT NEEDED
-  $MAGISK && [ ! -s $INFO ] && rm -f $INFO
-  
-  # SET PERMISSIONS
-  ui_print " "
-  ui_print "- Setting Permissions"
-  set_permissions
-}
-
-# UNINSTALL
-unity_uninstall() {
-  ui_print " "
-  ui_print "- Uninstalling"
-  
-  # REMOVE FILES
-  FILE=$INFO
-  $BOOTMODE && [ -f /sbin/.core/img/$MODID/$MODID-files ] && FILE=/sbin/.core/img/$MODID/$MODID-files
-  if [ -f $FILE ]; then
-    while read LINE; do
-      if [ "$(echo -n $LINE | tail -c 4)" == ".bak" ]; then
-        continue
-      elif [ -f "$LINE.bak" ]; then
-        mv -f $LINE.bak $LINE
-      else
-        rm -f $LINE
-        while true; do
-          LINE=$(dirname $LINE)
-          if [ "$(ls $LINE)" ]; then
-            break 1
-          else
-            rm -rf $LINE
-          fi
-        done
-      fi
-    done < $FILE
-    rm -f $FILE
-  else
-    $MAGISK || abort "   ! Mod not detected !"
-  fi
-  
-  $MAGISK && { rm -rf $MODPATH /sbin/.core/img/$MODID; rm -f $MOUNTPATH/.core/post-fs-data.d/$MODID-sysover.sh; }
-  
-  # RUN USER INSTALL SCRIPT
-  . $INSTALLER/common/uninstall.sh
-  
-  ui_print " "
-  ui_print "- Completing uninstall -"
-}
-
-##########################################################################################
-# (UN)INSTALL
-##########################################################################################
-
-# CHECK FOR OLD MAGISK, DETERMINE IF SYSTEM INSTALL OR MAGISK INSTALL, CHECK MAGISK VERSION (IF APPLICABLE)
-MINMAGISK=$(grep_prop minMagisk $INSTALLER/module.prop)
-if [ ! -d $MAGISKBIN ] && [ ! -d /data/magisk ]; then
-  MAGISK=false
-  ui_print "- System install detected"
-elif [ ! -f $MAGISKBIN/util_functions.sh ]; then
-  require_new_magisk
-else
-  ui_print "- Magisk install detected"
-  cp -f $MAGISKBIN/util_functions.sh $INSTALLER/common/unityfiles/util_functions_mag.sh
-  if $SYSOVERRIDE; then
-    ui_print "- Overriding paths for system install"
-    $BOOTMODE && { ui_print "   ! Magisk manager isn't supported!"; abort "   ! Install in TWRP !"; }
-    sed -i "s/-o ro/-o rw/g" $INSTALLER/common/unityfiles/util_functions_mag.sh
-    sysover_partitions
-  fi
-  . $INSTALLER/common/unityfiles/util_functions_mag.sh
-  [ ! -z $MAGISK_VER_CODE -a $MAGISK_VER_CODE -ge $MINMAGISK ] || require_new_magisk
-fi
-
-# MOUNT PARTITIONS AND DETECT VERSION/ARCHITECTURE
-mount_partitions
-api_level_arch_detect
-
-if $MAGISK; then
-  # SETUP BUSYBOX AND BINARIES
-  $BOOTMODE && boot_actions || recovery_actions
-  # GET THE VARIABLE REQSIZEM
-  request_zip_size_check "$ZIP"
-  # THIS FUNCTION WILL MOUNT $IMG TO $MOUNTPATH, AND RESIZE THE IMAGE BASED ON $REQSIZEM
-  mount_magisk_img
-fi
-
-# CHECK FOR MIN & MAX API VERSION
-[ -z $MINAPI ] || { [ $API -lt $MINAPI ] && require_new_api 'minimum'; }
-[ -z $MAXAPI ] || { [ $API -gt $MAXAPI ] && require_new_api 'maximum'; }
-
-# SET MODID and MODPATH variables
-[ -z $MODID ] && MODID=`grep_prop id $INSTALLER/module.prop`
-MODPATH=$MOUNTPATH/$MODID
-
-# INSERT MODID AND CUSTOM USER SCRIPT INTO MOD SCRIPT
-cp -f $INSTALLER/common/unityfiles/modid.sh $INSTALLER/common/unityfiles/post-fs-data.sh
-cp -f $INSTALLER/common/unityfiles/modid.sh $INSTALLER/common/unityfiles/service.sh
-sed -i -e "s/<MODID>/$MODID/" -e "/# CUSTOM USER SCRIPT/ r $INSTALLER/common/post-fs-data.sh" -e '/# CUSTOM USER SCRIPT/d' $INSTALLER/common/unityfiles/post-fs-data.sh
-sed -i -e "s/<MODID>/$MODID/" -e "/# CUSTOM USER SCRIPT/ r $INSTALLER/common/service.sh" -e '/# CUSTOM USER SCRIPT/d' $INSTALLER/common/unityfiles/service.sh
-mv -f $INSTALLER/common/unityfiles/post-fs-data.sh $INSTALLER/common/post-fs-data.sh
-mv -f $INSTALLER/common/unityfiles/service.sh $INSTALLER/common/service.sh
-
-# SET VARIABLES
-set_vars
-
-# ADD BLANK LINE TO END OF ALL COMMON FILES IF NOT ALREADY PRESENT
-for FILE in $INSTALLER/common/*.sh $INSTALLER/common/*.prop; do
-  [ "$(tail -1 $FILE)" ] && echo "" >> $FILE
-done
-
-# REMOVE OLD AML & MODS
-[ -f "$OLD_AML_VER" ] && remove_old_aml
-
-# LOAD USER VARS/FUNCTIONS
-unity_custom
-
-# DETERMINE MOD INSTALLATION STATUS
-if $MAGISK && ! $SYSOVERRIDE && [ -f "/system/addon.d/$MODID-files" -o -f "/system/etc/$MODID-files" ]; then
-  ui_print " "
-  ui_print "   ! Previous system override install detected!"
-  ui_print "   ! Removing...!"
-  $BOOTMODE && { ui_print "   ! Magisk manager isn't supported!"; abort "   ! Install in TWRP !"; }
-  mount -o rw,remount /system
-  [ -L /system/vendor ] && mount -o rw,remount /vendor
-  sysover_partitions
-  SYSOVERRIDE=true
-  set_vars
-  unity_uninstall
-  SYSOVERRIDE=false
-  set_vars
-  unity_install
-elif [ -f "$MOD_VER" ]; then
-  if [ $(grep_prop versionCode $MOD_VER) -ge $(grep_prop versionCode $INSTALLER/module.prop) ]; then
-    ui_print " "
-    ui_print "   ! Current or newer version detected!"
-    unity_uninstall
-  else
-    ui_print " "
-    ui_print "   ! Older version detected! Upgrading..."
-    unity_uninstall
-    unity_install
-  fi
-else
-  unity_install
-fi
-
-# COMPLETE (UN)INSTALL
-cleanup
+# Load Util_Functions, Add In-House Binaries to PATH, Start Bash Shell
+ARCH32=`getprop ro.product.cpu.abi | cut -c-3`
+[ -z $ARCH32 ] && ARCH32=`getprop ro.product.cpu.abi2 | cut -c-3`
+[ -z $ARCH32 ] && ARCH32=arm
+(tar -xf $INSTALLER/common/unityfiles.tar.gz -C $INSTALLER/common) || { echo "! Unable to extract unity files !"; exit 1; }
+chmod -R 755 $INSTALLER/common/unityfiles/$ARCH32
+echo $PATH | grep -q "$INSTALLER/common/unityfiles/$ARCH32" || export PATH=$INSTALLER/common/unityfiles/$ARCH32:$PATH
+bash $INSTALLER/common/unityfiles/util_functions.sh
